### ISSUE TITLE
Freeze on MTP transfer

### ISSUE THREAD

**Issue by Salamandar** [MeanEYE/Sunflower#256] opened 2016-09-26 11:57 UTC
Well I was transfering some 11GB on my phone and at 10GB Sunflower froze. Fortunately it was launched in a terminal and the traceback is :

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/sunflower/application/operation.py", line 1122, in run
    self._copy_file_list()
  File "/usr/share/sunflower/application/operation.py", line 1074, in _copy_file_list
    self._copy_file(file_name, source_path)
  File "/usr/share/sunflower/application/operation.py", line 945, in _copy_file
    dh.write(data)
  File "/usr/share/sunflower/application/plugins/file_list/gio_wrapper.py", line 73, in write
    self._resource.write(buff)
Error: Erreur libmtp : Erreur inconnue.
```

EDIT : Hm, and ctrl+C in the terminal returned :

```
^CTraceback (most recent call last):
  File "/usr/share/sunflower/Sunflower.py", line 75, in <module>
    process.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

but did not close SF.

**Comment by MeanEYE** [comment] 2016-09-26 13:59
Sunflower didn't close from Ctrl+C because GUI is started in separate thread. But I didn't expect error not to be caught there. Hm, strange. Thanks for reporting this. I don't know what would cause interruption during writing.

**Comment by Salamandar** [comment] 2016-09-29 19:46
It may be a simple error in libmtp not managed in SF. Or a MTP error not catched in libmtp.

**Comment by MeanEYE** [comment] 2020-05-18 13:01
I think this was an issue in upstream library. I tried testing this with version 0.4 and couldn't reproduce. For this reason I am closing this issue. If it's not fixed, please reopen.

Thanks!

**Closed by MeanEYE** 2020-05-18 13:01 UTC
Labels: bug
