### ISSUE TITLE
File Transfer Dialog Won't Close

### ISSUE THREAD

**Issue by mattcbro** [MeanEYE/Sunflower#114] opened 2015-05-18 22:29 UTC
If you transfer files between panes and the transfer fails for some reason,  it is impossible to close the file transfer dialog.  Pressing the x to close the dialogue window does nothing on my linux mint 17 machine.

 A good way to test this is to create permission problems so that the object directory can not be written to.

This issue applies to  Sunflower 0.2 (59)

**Comment by MeanEYE** [comment] 2015-05-19 10:01
This is due to multi-threading support as GUI has to be on a separate thread from file operation. It's better to treat underlying issue of what went wrong to cause dialog to be like this?

**Comment by niknah** [comment] 2015-05-20 02:32
I had this problem too.

In MoveOperation._remove_path, it says...

                               item_list.pop(item_list.index(path))

When item_list is a list of tuples.  Works, when I change it to...
                                item_list.pop(item_list.index((path, relative_path)))

This error only occurs when I'm moving from camera to local drive and the camera is read only.

**Comment by MeanEYE** [comment] 2015-05-20 15:20
Can you please start _Sunflower_ from the terminal and give me the output when this error occurs? We should catch most of the errors, including write issues.

**Comment by mattcbro** [comment] 2015-05-20 16:51
I created the error for this test,  by opening the same directory in 
each pane.  I then attempted to copy Matt.bib to itself,  which gave me 
a warning.  I then canceled the operation and got the dialog box which 
never goes away.

The error message occurs when I cancel the copy operation. Hopefully 
that is where the problem is occurring.
Here is the message.

    ~ $ sunflower
    Gkr-Message: secret service operation failed: The name
    org.freedesktop.secrets was not provided by any .service files
    Gkr-Message: secret service operation failed: The name
    org.freedesktop.secrets was not provided by any .service files
    /usr/share/sunflower/application/plugins/file_list/file_list.py:318:
    GtkWarning: IA__gdk_screen_get_setting: assertion 'GDK_IS_SCREEN
    (screen)' failed
       int(gtk.Settings().get_property('gtk-font-name').split()[-1])
    Exception in thread Thread-5:
    Traceback (most recent call last):
       File "/usr/lib/python2.7/threading.py", line 810, in
    __bootstrap_inner
         self.run()
       File "/usr/share/sunflower/application/operation.py", line 950,
    in run
         self._copy_file_list()
       File "/usr/share/sunflower/application/operation.py", line 918,
    in _copy_file_list
         self._copy_file(file_name, source_path)
       File "/usr/share/sunflower/application/operation.py", line 767,
    in _copy_file
         self._file_list.pop(self._file_list.index(file_name))
    ValueError: 'MattB.bib.bak' is not in list

    Gkr-Message: secret service operation failed: The name
    org.freedesktop.secrets was not provided by any .service files

I hope that helps.

-Matt

**Comment by MeanEYE** [comment] 2015-05-20 20:32
It does, thank you. Looks like file disappeared from the list. I'll have to investigate. Did you do anything out of the ordinary? Like source/destination was a USB disk or something like that?

**Comment by mattcbro** [comment] 2015-05-21 01:08
No it is just an ordinary directory on an internal hard drive formatted 
as ext4. The file is a simple text file.  I take it you are not able to 
directly reproduce the problem on your build machines?

-Matt

**Comment by ArseniyK** [comment] 2015-05-21 06:01
Did you try develop version?

**Comment by niknah** [comment] 2015-05-21 06:36
_file_list is an array of tuples.  In the file where it crashed, change the line too...

			self._file_list.pop(self._file_list.index((file_name, relative_path)))

It looks fixed in some places, but this problem is still in a lot of other places in operation.py, sometimes _file_list is item_list

**Comment by MeanEYE** [comment] 2015-05-25 11:09
Can you please @niknah confirm you are using the latest source?

**Comment by niknah** [comment] 2015-05-25 11:26
Yes, to duplicate this problem, go to a read only folder on one side.  Move the file to your local folder, press "skip" when it asks and it'll crash and the dialog will be stuck.

It works when I  change the below line to...

                                item_list.pop(item_list.index((path,relative_path)))


Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/hankin/Downloads/Sunflower/application/operation.py", line 1195, in run
    self._delete_file_list()
  File "/home/hankin/Downloads/Sunflower/application/operation.py", line 1098, in _delete_file_list
    self._remove_path(item[0], self._file_list, item[1])
  File "/home/hankin/Downloads/Sunflower/application/operation.py", line 1009, in _remove_path
    item_list.pop(item_list.index(path))

**Comment by MeanEYE** [comment] 2015-05-25 11:27
Ah, okay. _Skip_ part was important. Thanks.

**Comment by joshas** [comment] 2020-05-21 16:36
@MeanEYE , I cannot reproduce this issue with latest develop version. Issue can be closed.

**Comment by MeanEYE** [comment] 2020-05-21 21:22
Thank you for testing. I was unable to reproduce it either.

**Closed by MeanEYE** 2020-05-21 21:22 UTC
Labels: bug
