### ISSUE TITLE
Current operations

### ISSUE THREAD

**Issue by LionelR** [MeanEYE/Sunflower#238] opened 2016-05-20 07:17 UTC
Enhancement : Put the current operations (copy, move, ...) in a visible panel on the main window, not in the menu bar. That is, we can have a look on the pending operations while working on other files.
In the same way, set the ability to really close the modal operations windows.

**Comment by LionelR** [comment] 2016-05-20 17:01
For the close modal operations windows, I have to chose and reopen SF to get it.

**Comment by therealrobster** [comment] 2016-11-17 08:27
I second this request.  Coming from another file manager in OS X I like the progress bar showing the progress of the total combined operations.  I can click on that progress bar, it drops down then shows all the operations in progress.  In comparison, sunflower currently has mutliple dialogs open that I have to try and cycle through to find the one I want to cancel from the queue or pause etc.   I hope that makes sense?

**Comment by MeanEYE** [comment] 2016-11-17 09:19
Versions prior to 0.4 were built in GTK2 and to achieve this I would have to build custom widget which would get outdated by 0.4. That's why this enhancement is scheduled for 0.4 which will be built in GTK3. I completely agree that operations should be visible from the main window and not hidden in some obscure menu.

**Comment by therealrobster** [comment] 2016-11-17 23:32
OK that makes perfect sense.  For a great example of this kind of system in
use check out Forklift for OS X.  It has a brilliant implementation of the
system.

**Comment by joshas** [comment] 2019-08-02 12:46
Duplicate of #50

**Closed** 2019-08-04 11:29 UTC
Labels: duplicate, enhancement
