### ISSUE TITLE
Add quick-view mode

### ISSUE THREAD

**Issue by strangeattr** [MeanEYE/Sunflower#281] opened 2017-09-27 20:37 UTC
One of the handiest features of other 2-panel file managers is the quick view mode - automatically displaying contents of the file under cursor in the opposite panel (traditionally triggered on by Ctrl+Q or Ctrl+X,Q).

**Comment by MeanEYE** [comment] 2017-09-27 20:52
This is a duplicate of #61. It's planned once we switch to GTK3.

**Closed by MeanEYE** 2017-09-27 20:52 UTC
Labels: duplicate
