### ISSUE TITLE
Trash can file list doesn't refresh after emptying trash

### ISSUE THREAD

**Issue by joshas** [MeanEYE/Sunflower#328] opened 2019-04-10 18:01 UTC
Delete some files to "Trash can". Open "Trash can" tab and press "Empty trash" button. After confirmation all items in trash can list will remain on display. You need to reload list manually to see actual state of trash can.

**Comment by joshas** [comment] 2019-12-10 21:11
Trash list monitor is not working, because for URIs (like trash:///) Gio.File.new_for_uri() function should be used instead of Gio.File.new_for_path() .
https://github.com/MeanEYE/Sunflower/blob/2c5d221619fc954826c899ffd89a5b95e6442dcb/sunflower/plugins/file_list/local_monitor.py#L30

After fixing that, I get errors when deleting files and emptying trash, probably related to incorrect signal handling on trash items. Should we implement a standalone "trash monitor"?

**Comment by MeanEYE** [comment] 2019-12-10 21:28
We should first check which signals are being fired. GioMonitor should be enough
but it's possible there are custom signals. If there are indeed custom signals,
then we can implement custom monitor.
-- 
Mladen Mijatov
Head of R&D, Way2CU

Key ID: 4096R/83EFD5A0 2013-08-18

**Comment by joshas** [comment] 2019-12-12 21:31
The main issue is in _directory_changed() function in file_list.py, where gio_provider.TrashProvider is changed to local_provider.LocalProvider . After that files moved to trash are displayed as unknown type and "Empty trash" function is broken, until trash list view is reloaded with Ctrl+R.
https://github.com/MeanEYE/Sunflower/blob/2c5d221619fc954826c899ffd89a5b95e6442dcb/sunflower/plugins/file_list/file_list.py#L1382

I had to temporary disable provider caching, just to make sure it was the culprit. Also removed function that skips parent dir. There's a big probability that this "fix" will break some other functionality.
Here's my current WIP code: https://github.com/joshas/Sunflower/commit/2bb61fce616d4356b8012aa7aab9bbb079ff8393

I would like to get some pointers, how to correctly fix issue with provider . Ultimately we'll need to make sure that all other providers work correctly.

**Comment by MeanEYE** [comment] 2019-12-15 15:32
Did you take a look at what happens to path. `LocalProvider` shouldn't be assigned to trash directory simply because protocol is different.

**Comment by joshas** [comment] 2019-12-16 19:24
When parent_path is None `get_provider(parent_path)` function presumes that parent path is "root" ( / ) and that's how LocalProvider ends up being assigned to TrashList.

**Comment by MeanEYE** [comment] 2019-12-17 04:41
That's a very specific issue and that whole code I am not proud of. Finding provider through `parent_path` is not that great of an idea since `_directory_changed` operates on a current directory which current provider applies to. Am thinking that just calling `self.get_provider()` without any parameters should solve the issue and there shouldn't be any regressions with expanded directories either.

**Closed** 2020-04-25 17:51 UTC
Labels: bug
