### ISSUE TITLE
0.3.61-1 RPM needs 2 corrections

### ISSUE THREAD

**Issue by ieanuc01** [MeanEYE/Sunflower#193] opened 2016-02-12 07:12 UTC
/usr/share/sunflower/Sunflower.py needs to be executable (644 -> 755)

module python-chardet needs to be added as a dependency (on Fedora, it's in the fedora repo)

**Comment by Choens** [comment] 2016-03-11 03:04
I'll second the permissions issue. Just installed the Fedora RPM and had to chmod Sunflower.py to get it to start.

**Comment by MeanEYE** [comment] 2016-03-11 11:41
Can you please test with this RPM:
http://sunflower-fm.org/temp/sunflower-0.3.61-1.noarch.rpm

I've fixed this but I don't have Fedora system so I need confirmation. Thanks!

**Comment by Choens** [comment] 2016-03-11 12:54
Same permissions error:

    [andy@optimus ~]$ sunflower 
    /usr/bin/sunflower: line 3: /usr/share/sunflower/Sunflower.py: Permission
denied
    /usr/bin/sunflower: line 3: exec: /usr/share/sunflower/Sunflower.py: cannot
    execute: Permission denied
    [andy@optimus ~]$ 


-----Original Message-----

**Comment by ieanuc01** [comment] 2016-03-12 09:44
I also still had the permission problem.  However, python-chardet WAS installed automatically during the Sunflower install.  FWIW, python-chardet is installed by default on the XFCE spin of Fedora 23 workstation, but not on the default Gnome version.

**Comment by Choens** [comment] 2016-03-12 12:20
I cloned master onto my laptop last month and my rpm had the fans problem.
But I can't figure out why.

**Comment by MeanEYE** [comment] 2016-03-12 16:42
Well the issue is [here](https://github.com/MeanEYE/Sunflower/blob/develop/dist/sunflower.spec#L21). Whole Sunflower directory is copied to `/usr/share`. So I added 

```
install -Dm755 "build/Sunflower/Sunflower.py"  "$RPM_BUILD_ROOT/usr/share/sunflower/"
```

but it looks like it's not copying if the file already exists. So I'll just have to specify permission manually with `%attr`.

**Comment by csmart** [comment] 2016-04-27 01:25
@MeanEYE yeah you can just add this to %files:

`%attr(0755,root,root) /usr/share/sunflower/Sunflower.py`

You'll just get a warning about it being a duplicate, but it will work.

**Comment by MeanEYE** [comment] 2016-04-27 07:28
Oh, thanks @csmart. That will do.

**Comment by MeanEYE** [comment] 2016-04-29 15:03
Well, turns out I've already applied fix @csmart suggested. This issue was reopened so I assumed that fix didn't solve the problem. Did anyone tried building rpm after this fix was applied?

**Comment by ieanuc01** [comment] 2016-04-30 06:36
I tried re-installing the rpm, but unfortunately:
1. still had to manually chmod 755 Sunflower.py
2. had to manually install python-chardet (it installed automatically the last time I did the install).
Re: the "reopen".  That was the result of my error trying to post a reply; I clicked "Close and comment" instead of "Comment", so then had to reopen.

**Comment by ieanuc01** [comment] 2016-04-30 06:54
Ignore my comment 2. in the previous post.  I forgot to download the rpm from the /temp folder, so installed the wrong one (from the normal "Download" page).  With the correct rpm, python-chardet DID install automatically, but I still had to chmod Sunflower.py

**Comment by csmart** [comment] 2016-04-30 23:12
The change was made to master in March:
https://github.com/MeanEYE/Sunflower/blob/master/dist/sunflower.spec#L31

But this change is not in develop branch (which is the default):
https://github.com/MeanEYE/Sunflower/blob/develop/dist/sunflower.spec#L27

**Comment by csmart** [comment] 2016-04-30 23:13
Master commit:
https://github.com/MeanEYE/Sunflower/commit/42ffb4f66446db25c0523d6c35e9f93ce046d5dc

**Comment by csmart** [comment] 2016-04-30 23:24
The master branch was merged to develop here 529cc8cc760ddab64fc6037e6fef1991020ea3fe and then after that, master had 4 new commits:
42ffb4f66446db25c0523d6c35e9f93ce046d5dc
e7add419991a353c86ae1ec04f1e47a6eb9fbe93
083319c17d4bd85b43025f9651844d019a2a9162 - this is the spec file fix
f2fa96ab0a166f459d598e7c42d3d3c469cbed3d

So a simple merge of master into develop should solve the problem and bring in those 4 commits.

**Comment by MeanEYE** [comment] 2016-05-01 07:51
Ah, you are right. Somehow I missed. Thanks!

**Comment by MeanEYE** [comment] 2020-05-18 12:57
I am assuming this is fixed now. Also, new version is out and should have these fixed.

**Closed by MeanEYE** 2020-05-18 12:57 UTC
Labels: bug, critical
