### ISSUE TITLE
I can't delete

### ISSUE THREAD

**Issue by Gallipo** [MeanEYE/Sunflower#171] opened 2016-01-19 00:06 UTC
Hello,
when I try to delete a file, a progress-bar appears but then nothing happens.
I'm running Sunflower 0.3 (60) on Ubuntu 15.10
This is the console-output:
```~$ sunflower
    Traceback (most recent call last):
      File "/usr/share/sunflower/application/accelerator_group.py", line 96, in _handle_activate
        result = callback_method(widget, data)
      File "/usr/share/sunflower/application/plugins/file_list/file_list.py", line 867, in _delete_files
        operation.set_operation_queue(queue_name)
    UnboundLocalError: local variable 'queue_name' referenced before assignment```

**Comment by MeanEYE** [comment] 2016-01-19 08:30
Thanks. I wonder how I didn't run into this. This will have to be patched and released as soon as possible.

**Comment by Gallipo** [comment] 2016-01-19 11:52
I don't know if this is relevant: 
When I installed Sunflower the first time, I did it via the ppa:atareao. But that wasn't the most recent release, so I downloaded the ubuntu *.deb from the projects website and installed it with `dpkg -i ...`
Maybe that messed things up?

**Comment by MeanEYE** [comment] 2016-01-19 11:54
Atareao PPA is severly outdated and they had issues packaging before. However if you installed out `deb` file from official site you should be fine. I did see where the issue is, and indeed it is a bug.

**Comment by Gallipo** [comment] 2016-01-19 11:56
Wow, man, thats what I call a quick respond. 
Thanks for this nice piece of software, you'r doing great work.

**Comment by MeanEYE** [comment] 2016-01-19 11:58
Am working and get notifications quite fast. :) Thanks for kind words. This should be fixed soon and I'll release hotfix. I am just baffled how it went past me since I use this all the time.

**Comment by MikeWallaceDev** [comment] 2016-01-25 22:31
Just to add some information, I didn't install via a package. I cloned the repo.

**Comment by MikeWallaceDev** [comment] 2016-01-25 23:19
Ok, I looked at the code and the problem seems to be that "queue_name" is only initialized if the user shows the confirmation dialog and chooses a queue. 
@Gallipo  A workaround is to enable the confirmation box in the settings and choose the default queue. The delete operation will then work.

**Comment by MeanEYE** [comment] 2016-01-26 14:04
So that's the reason why I didn't run in to that bug. It's a simple fix anyway. Thanks @MikeWallaceDev.

**Comment by MeanEYE** [comment] 2016-01-30 09:11
One line fix. :) Silly.

**Closed by MeanEYE** 2016-01-30 09:11 UTC
Labels: bug, critical
