### ISSUE TITLE
Doesn't run on Fedora

### ISSUE THREAD

**Issue by pchmykh** [MeanEYE/Sunflower#522] opened 2024-01-21 13:16 UTC
Here is output:
~$ sunflower 
Traceback (most recent call last):
  File "/usr/local/bin/sunflower", line 4, in <module>
    runpy.run_module('sunflower', run_name='__main__', alter_sys=True)
  File "<frozen runpy>", line 222, in run_module
  File "<frozen runpy>", line 142, in _get_module_details
ImportError: No module named sunflower

**Comment by MeanEYE** [comment] 2024-01-22 11:32
How did you install?

**Comment by pchmykh** [comment] 2024-01-22 18:51
I have downloaded https://sunflower-fm.org/pub/sunflower-0.5.63-1.noarch.rpm file from https://sunflower-fm.org/download page.

**Comment by MeanEYE** [comment] 2024-01-22 21:29
Ah, this is a duplicate of #512. Basically I fail at detecting Fedora's default Python directory. Am gonna close this one so you can follow the other one. I'll try to get this fixed as soon as I can find time.

**Closed as completed by MeanEYE** 2024-01-22 21:29 UTC
